name: A workflow for my Hello World file
on:
 - push
 - workflow_dispatch

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./action-a
        with:
          MY_NAME: "Nike"
      - run: echo This is a secret ${{ secrets.MY_SECRET }}
      
  devDeploy:
     runs-on: ubuntu-latest
     environment:
       name: DEV
       
     steps:
       - run: echo Welcome to Dev
  
